### PR TITLE
Allow overwrites for non-virtual components

### PR DESCRIPTION
**Pull request by jonasfj**
I think we already considered something like this... But I'm realizing that it's useful testing...

As it basically, allows us to inject a MockObject in place of initializing the original object..

Generally, I don't like mocking things... I just prefer complete tests, but not everybody agrees.. This seems like an elegant way of doing it...

Currently playing with this for tc-hooks, as I didn't want to fix configs for dustin without actually doing it right :)

### CODE REVIEW

**Comment by jhford** [comment]
I like this approach because it makes Sinon unneeded in a lot of places.  It's too bad that we don't have .gitignore and .npmignore easy to use, but please don't add the output of bable to the repository.  I'd say add it to .gitignore, but then NPM wouldn't package it for distribution.  Yay packaging!

**Comment by jonasfj** [comment]
@jhford,
Yeah, lets ADD both .gitignore and .npmignore.
We just have to be careful to exlude local configs in both... The other thing is too painful..

**Comment by jonasfj** [comment]
And thanks for noticing i added lib/ I'll fix that..

**Comment by jonasfj** [comment]
@jhford, added a few extra nits... too..

**Comment by jhford** [comment]
915dff38f5f1eaa059f078fdd9d0d46dbbd03b72

Merged, thanks!

**Pull request closed without merging**
